# see https://github.com/compose-spec/compose-spec/blob/master/spec.md
# see https://github.com/opencontainers/image-spec/blob/master/annotations.md
services:
  server:
    build: server
    restart: on-failure
    environment:
      SPIFFE_ENDPOINT_SOCKET: unix:///tmp/spire-agent/public/api.sock
      SERVER_SPIFFE_ID: spiffe://spire.test/example-server
    volumes:
      - /tmp/spire-agent/public/api.sock:/tmp/spire-agent/public/api.sock
    ports:
      - "8443:443"
  client:
    build: client
    restart: on-failure
    environment:
      SPIFFE_ENDPOINT_SOCKET: unix:///tmp/spire-agent/public/api.sock
      CLIENT_SPIFFE_ID: spiffe://spire.test/example-client
    volumes:
      - /tmp/spire-agent/public/api.sock:/tmp/spire-agent/public/api.sock
    ports:
      - "8080:80"
